repos:
- repo: local
  hooks:
  - id: py3-format
    name: Python 3 format
    entry: python -m tools.lint py3-format
    language: system
    pass_filenames: false
  - id: py3-lint
    name: Python 3 lint
    entry: python -m tools.lint py3-lint
    language: system
    pass_filenames: false
  - id: py27-lint
    name: Python 2.7 lint
    entry: python -m tools.lint py27-lint
    language: system
    pass_filenames: false
  - id: py27-format
    name: Python 2.7 format
    entry: python -m tools.lint py27-format
    language: system
    pass_filenames: false
    stages: [manual]